In [1]:
## Imported the required libraries.
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
## Opening the data in python
df=pd.read_csv('01 Loan_default.csv')

df.info()       ## Basic info
df.describe()   ## Statistical info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   LoanID           255347 non-null  object
 1   Age              255347 non-null  int64
 2   Income           255347 non-null  int64
 3   LoanAmount       255347 non-null  int64
 4   CreditScore      255347 non-null  int64
 5   Months Employed  255347 non-null  int64
 6   NumCreditLines   255347 non-null  int64
 7   InterestRate     255347 non-null  float64
 8   LoanTerm         255347 non-null  int64
 9   DTIRatio         255347 non-null  float64
 10  Education        255347 non-null  object
 11  EmploymentType   255347 non-null  object
 12  Marital Status   255347 non-null  object
 13  HasMortgage      255347 non-null  object
 14  Has Dependents   255347 non-null  object
 15  LoanPurpose      255347 non-null  object
 16  HasCoSigner      255347 non-null  object
 17  Default          255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB

,Age,Income,LoanAmount,CreditScore,Months Employed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [3]:
df.shape        ## No. of Rows and Columns

(255347, 18)

In [4]:
df.head()       ## Top 5 rows

,LoanID,Age,Income,LoanAmount,CreditScore,Months Employed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,Marital Status,HasMortgage,Has Dependents,LoanPurpose,HasCoSigner,Default
0,OU7PMVEJI7,30,106648,249844,586,71,1,25.0,60,0.61,High School,Part-time,Single,No,Yes,Other,No,0
1,C54BGR0QCS,36,100912,237113,633,52,4,25.0,48,0.11,Bachelor's,Self-employed,Single,Yes,No,Other,No,0
2,6G7J7QAHLD,19,97491,225162,457,109,3,25.0,12,0.74,Bachelor's,Self-employed,Divorced,Yes,Yes,Business,Yes,0
3,REDX379HK0,42,84924,220442,613,66,1,25.0,24,0.53,PhD,Full-time,Married,Yes,No,Auto,No,0
4,M62QY9YL8C,45,27679,213350,781,118,2,25.0,24,0.67,PhD,Self-employed,Single,No,Yes,Education,Yes,0

In [5]:
## Identification of nulls
df.isnull().sum()

LoanID             0
Age                0
Income             0
LoanAmount         0
CreditScore        0
Months Employed    0
NumCreditLines     0
InterestRate       0
LoanTerm           0
DTIRatio           0
Education          0
EmploymentType     0
Marital Status     0
HasMortgage        0
Has Dependents     0
LoanPurpose        0
HasCoSigner        0
Default            0
dtype: int64

In [6]:
## Identification of any duplicate values
df.duplicated().sum()           ##np.int64(0) this means no duplicates

np.int64(0)

In [7]:
## Default Counts 
df['Default'].value_counts()  ## [0 No Defaults, 1 Defaults]

Default
0    225694
1     29653
Name: count, dtype: int64

In [8]:
## Default %
df['Default'].value_counts(normalize=True)*100

Default
0    88.387175
1    11.612825
Name: proportion, dtype: float64

In [9]:
## Co-Relation
df.corr(numeric_only=True)

# This helps identify:
# which variables influence default
# relationships between financial variables

,Age,Income,LoanAmount,CreditScore,Months Employed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
Age,1.000000,-0.001244,-0.002213,-0.000548,-0.000341,-0.000890,-0.001127,0.000263,-0.004689,-0.167783
Income,-0.001244,1.000000,-0.000865,-0.001430,0.002675,-0.002016,-0.002303,-0.000998,0.000205,-0.099119
LoanAmount,-0.002213,-0.000865,1.000000,0.001261,0.002817,0.000794,-0.002291,0.002538,0.001122,0.086659
CreditScore,-0.000548,-0.001430,0.001261,1.000000,0.000613,0.000016,0.000436,0.001130,-0.001039,-0.034166
Months Employed,-0.000341,0.002675,0.002817,0.000613,1.000000,0.001267,0.000096,-0.001166,0.001765,-0.097374
NumCreditLines,-0.000890,-0.002016,0.000794,0.000016,0.001267,1.000000,-0.000297,-0.000226,-0.000586,0.028330
InterestRate,-0.001127,-0.002303,-0.002291,0.000436,0.000096,-0.000297,1.000000,0.000892,0.000575,0.131273
LoanTerm,0.000263,-0.000998,0.002538,0.001130,-0.001166,-0.000226,0.000892,1.000000,0.002273,0.000545
DTIRatio,-0.004689,0.000205,0.001122,-0.001039,0.001765,-0.000586,0.000575,0.002273,1.000000,0.019236
Default,-0.167783,-0.099119,0.086659,-0.034166,-0.097374,0.028330,0.131273,0.000545,0.019236,1.000000

Simple Interpretation for Your Project
Older, higher-income, and longer-employed borrowers tend to default less.
Higher interest rates and larger loan amounts slightly increase default risk.
Most variables show very weak correlations, meaning default likely depends on multiple combined factors rather than a single variable.

“The correlation analysis shows that Age has the strongest negative relationship with default (-0.17), meaning older borrowers tend to default less. Interest rate has the strongest positive correlation (0.13), indicating that higher interest rates increase the probability of default. However, most variables show weak correlations, suggesting that **loan default is influenced by multiple factors rather than a single variable.”

In [10]:
## Income Group
df['IncomeGroup'] = pd.cut(
    df['Income'],
    bins=[0,30000,50000,100000,130000,150000],
    labels=['Low','Lower-Mid','Middle','Upper-Mid','High']
)

df['IncomeGroup'].value_counts()

IncomeGroup
Middle       94683
Upper-Mid    56828
High         37737
Lower-Mid    37694
Low          28405
Name: count, dtype: int64

In [11]:
## Credit Score Group
df['CreditScoreGroup']=pd.cut(
    df['CreditScore'],
        bins=[200,580,670,740,800,850],
        labels=['Poor','Fair','Good','Very Good','Excellent']
)

df['CreditScoreGroup'].value_counts()

CreditScoreGroup
Poor         130708
Fair          41877
Good          31991
Very Good     27771
Excellent     23000
Name: count, dtype: int64

In [12]:
## Age Group
df['AgeGroup']=pd.cut(
    df['Age'],
    bins=[15,30,40,50,60,70],
    labels=['18-30','31-40','41-50','51-60','60+']
)

df['AgeGroup'].value_counts()

AgeGroup
18-30    63577
31-40    49593
41-50    49003
51-60    48972
60+      44202
Name: count, dtype: int64

In [13]:
## Loan Size Group
df['LoanSize']=pd.cut(
    df['LoanAmount'],
    bins=[0,50000,100000,150000,200000,250000],
    labels=['Very Small', 'Small', 'Medium', 'Large', 'Very Large']
)

df['LoanSize'].value_counts()

LoanSize
Very Large    52419
Large         51981
Small         51977
Medium        51879
Very Small    47091
Name: count, dtype: int64

In [14]:
## Converting Default Column to yes no format 
df['DefaultStatus']=df['Default'].map({0:'No', 1:'Yes'})

In [15]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,Months Employed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,...,HasMortgage,Has Dependents,LoanPurpose,HasCoSigner,Default,IncomeGroup,CreditScoreGroup,AgeGroup,LoanSize,DefaultStatus
0,OU7PMVEJI7,30,106648,249844,586,71,1,25.0,60,0.61,...,No,Yes,Other,No,0,Upper-Mid,Fair,18-30,Very Large,No
1,C54BGR0QCS,36,100912,237113,633,52,4,25.0,48,0.11,...,Yes,No,Other,No,0,Upper-Mid,Fair,31-40,Very Large,No
2,6G7J7QAHLD,19,97491,225162,457,109,3,25.0,12,0.74,...,Yes,Yes,Business,Yes,0,Middle,Poor,18-30,Very Large,No
3,REDX379HK0,42,84924,220442,613,66,1,25.0,24,0.53,...,Yes,No,Auto,No,0,Middle,Fair,41-50,Very Large,No
4,M62QY9YL8C,45,27679,213350,781,118,2,25.0,24,0.67,...,No,Yes,Education,Yes,0,Low,Very Good,41-50,Very Large,No

In [16]:
df.to_csv('LoanPythonCleanedData.csv', index=False)